// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalHBnti6rafbQrRK8p9NBiBj7VrvdQkA',
    appId: '1:113153603225:web:5055da4e4425486b752a08',
    messagingSenderId: '113153603225',
    projectId: 'chat-app-9428a',
    authDomain: 'chat-app-9428a.firebaseapp.com',
    storageBucket: 'chat-app-9428a.appspot.com',
    measurementId: 'G-GVL9QMV53H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAzH-8Fyt1sv1p2qAJ5PyDylGnaqtJZk',
    appId: '1:113153603225:android:f807ea489fe3226f752a08',
    messagingSenderId: '113153603225',
    projectId: 'chat-app-9428a',
    storageBucket: 'chat-app-9428a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEcq6LOfJHUvaso1Y4-jJYX9ehuz8t20A',
    appId: '1:113153603225:ios:c635a1366fb229f3752a08',
    messagingSenderId: '113153603225',
    projectId: 'chat-app-9428a',
    storageBucket: 'chat-app-9428a.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
